let suggestions = [
    "Mask",
    "Jeans",
    "Toys",
    "Bluetooth Speakers",
    "Laptops",
    "Smart TV",
    "Shoes",
    "Watch",
    "Handbags",
    "Nivea Body Milk Lotion",
    "Headphones",
    "IPhone",
    "Bedsheets",
    "Mobile Phones",
    "Oxyzen Cylinder",
    "Sanitizer",
    "Vaseline",
    "Nivea Soft",
    "Mamaearth Onion Hair Oil",
    "Dettol",
    "Soap",
    "Shirt",
    "Shampoo",
    "Salt",
    "Coffee",
    "Mixer Grinders",
    "Chromebook",
    "Macbook",
    "Sofas",
    "Bottles",
    "Office Chairs",
    "Shirt",
    "Shampoo",
    "Salt",
    "Coffee",
    "Mixer Grinders",
];